### ISSUE TITLE
Aika näkyy 12h-formaatissa

### ISSUE THREAD

**Issue by Aikain** [ikafi/stats#8]
Pitäisi vaihtaa h ->H

https://github.com/ikafi/stats/blob/3ef060194ec966a200187d1af3226b7cab7c5767/ika-stats/src/main/java/fi/gosu/ika/stats/domain/SpyReport.java#L44

http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html

**Comment by Joppe151617** [comment]
Muutettu seuraavassa versiossa.
